### ISSUE TITLE
Trying to connect this to Next-auth

### ISSUE THREAD

**Issue by redimongo** [noreajs/oauth-v2-provider-me#7]
I am wondering how do I create a custom Provider for Next-Auth using this as my oauth v2 provider?

basically their documentation is saying to make connections like below, however I am not sure how that will work with oauth-v2-provider-me

```
{
  id: "google",
  name: "Google",
  type: "oauth",
  wellKnown: "https://accounts.google.com/.well-known/openid-configuration",
  authorization: { params: { scope: "openid email profile" } },
  idToken: true,
  checks: ["pkce", "state"],
  profile(profile) {
    return {
      id: profile.sub,
      name: profile.name,
      email: profile.email,
      image: profile.picture,
    }
  },
}
```

**Comment by lambou** [comment]
Hi @redimongo , Sorry for the late response. Next-auth is a solution for next.js applications.

oauth-v2-provider-me is not an Oauth provider as defined in Next-Auth specification.

You use this package only when you want your node.js app to support oauth v2 authentication.
